version: '3.8' 

services:
  hospital-front:
    image: hospital-front:lastest
    depends_on:
      - "hospital-api"
    build:
      context: ../../patient-portal-front/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks: 
      - application

  hospital-api:
    image: hospital-api:latest
    depends_on:
      - "database"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"     
    environment:
      DB_CONNECTION_STRING: "port=5432;database=MyWebApi.Dev;username=admin;password=ftn"
    networks:
      - application
  
  database: 
    image: postgres:latest
    ports:
      - "5555:5432"
    restart: always
    volumes:
      - type: volume
        source: db_volume
        target: /var/lib/postgresql/data
      #- type: bind
        #source: ./dbscripts/medicine.sql 
        #target: /docker-entrypoint-initdb.d/medicne.sql
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "ftn"
      POSTGRES_DB: "MyWebApi.Dev"
    networks:
      - application
volumes:
  db_volume:
    name: database

networks:
  application:
    name: application
    driver: bridge