name: unit-testing
on:
  push:
  pull_request:


jobs:
  Run-Unit-Tests:

    runs-on: ubuntu-latest
    env:
      SOLUTION_DIRECTORY: PharmacyApplication
      SOLUTION_DIRECTORY2: WebAppCore/HospitalTests/HospitalTests.csproj
      SOLUTION_DIRECTORY3: WebAppCore/IntegrationTests/IntegrationTests.csproj


    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dotnet restore ${SOLUTION_DIRECTORY}
      - name: Build
        run: dotnet build ${SOLUTION_DIRECTORY} --configuration Release --no-restore
      - name: Test
        run: dotnet test ${SOLUTION_DIRECTORY} --no-restore --verbosity quiet --filter FullyQualifiedName!~IntegrationTests

      - name: Install dependencies2
        run: dotnet restore ${SOLUTION_DIRECTORY2}
      - name: Build2
        run: dotnet build ${SOLUTION_DIRECTORY2} --configuration Release --no-restore
      - name: Test2
        run: dotnet test ${SOLUTION_DIRECTORY2} --no-restore --verbosity quiet --filter FullyQualifiedName!~IntegrationTests


      - name: Install dependencies3
        run: dotnet restore ${SOLUTION_DIRECTORY3}
      - name: Build3
        run: dotnet build ${SOLUTION_DIRECTORY3} --configuration Release --no-restore
      - name: Test3
        run: dotnet test ${SOLUTION_DIRECTORY3} --no-restore --verbosity quiet --filter FullyQualifiedName!~IntegrationTests
