name: unit-testing
on:
  push:
  pull_request:


jobs:
  Run-Unit-Tests:

    runs-on: ubuntu-latest
    env:
      PHARMACY_PROJECT_SOLUTION: PharmacyApplication
      HOSPITAL_PROJECT_SOLUTION: WebAppCore/HospitalTests/HospitalTests.csproj
      INTEGRATION_PROJECT_SOLUTION: WebAppCore/IntegrationTests/IntegrationTests.csproj


    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: dotnet restore ${PHARMACY_PROJECT_SOLUTION}
      - name: Build
        run: dotnet build ${PHARMACY_PROJECT_SOLUTION} --configuration Release --no-restore
      - name: Test
        run: dotnet test ${PHARMACY_PROJECT_SOLUTION} --no-restore --verbosity quiet --filter FullyQualifiedName!~IntegrationTests

      - name: Install dependencies2
        run: dotnet restore ${HOSPITAL_PROJECT_SOLUTION}
      - name: Build2
        run: dotnet build ${HOSPITAL_PROJECT_SOLUTION} --configuration Release --no-restore
      - name: Test2
        run: dotnet test ${HOSPITAL_PROJECT_SOLUTION} --no-restore --verbosity quiet --filter FullyQualifiedName!~IntegrationTests


      - name: Install dependencies3
        run: dotnet restore ${INTEGRATION_PROJECT_SOLUTION}
      - name: Build3
        run: dotnet build ${INTEGRATION_PROJECT_SOLUTION} --configuration Release --no-restore
      # - name: Test3
      #   run: dotnet test ${INTEGRATION_PROJECT_SOLUTION} --no-restore --verbosity quiet --filter FullyQualifiedName!~IntegrationTests
